version: "3"
services: 
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: schoolsystem
      POSTGRES_USER: schoolsystem
      POSTGRES_DB: schoolsystem
    volumes:
      - ./src/schema:/docker-entrypoint-initdb.d 
    ports:
      - 5432:5432
  webserver:
    build: .
    depends_on:
      - database
    volumes: 
      - .:/app
    ports:
      - 3000:3000

      # FIXME: Instead of .env set environment here



      # FIXME: https://docs.docker.com/compose/compose-file/05-services/#healthcheck
      # Maybe start containers with healthchecks
