version: "3"
services: 
  schoolsystem:
    image: postgres
    environment:
      POSTGRES_PASSWORD: schoolsystem
      POSTGRES_USER: schoolsystem
      POSTGRES_DB: schoolsystem
    volumes:
      - /home/ayyubi/SchoolSystem/schema:/docker-entrypoint-initdb.d 
  app:
    image: schoolsystemdocker 
    ports:
      - 3000:3000
      - 3001:3001
